#!/bin/bash
if [ -z "$PYFILE" ]; then
	echo "Please set the PYFILE environment variavle"
	exit 1
fi

rm -r __pycache__/

python3 -m py_compile "$PYFILE"

mv __pycache__/*.pyc "${PYFILE}c"

echo "Output file name: ${PYFILE}c"

